### ISSUE TITLE
Issue with subscribing with O365

### ISSUE THREAD

**Issue by breadcan** [offenesdresden/dresden-ratsinfo#1]
I tried to subscribe the meeting.ics in O365 but got errors. I tried a shorter version with one event and there it seems to have issues with the end date of the event:

```
BEGIN:VEVENT
METHOD:PUBLISH
CLASS:PUBLIC
UID:meeting-http://oparl.dresden.de/bodies/0001/meetings/13384@ratsinfo.dresden.de
URL:https://ratsinfo.dresden.de/si0050.asp?smcred=20&__ksinr=13384
DTSTART:20240916T193000
DTEND:20240916T000000
```

The end date is I guess now before the start date. If I try 20:00 as end date it imports the ics...

**Comment by astro** [comment]
It's already wrong [in the source data.](https://github.com/offenesdresden/dresden-ratsinfo/blob/master/meetings/13384.json)

I've added [a workaround to the scraper](https://github.com/offenesdresden/ratsinfo-scraper/commit/75315d8d0d53fab93ccf6d7d26dae36bbe50fa3d). The fixed file should be updated in a few hours when the scraper finishes.
